### ISSUE TITLE
NER 데이터 전처리 관련하여 궁금한 것이 있습니다.

### ISSUE THREAD

**Issue by ZIZUN** [sooftware/nlp-tasks#1]
코드를 봤는데, NER 데이터 전처리 시에
만일 label이 PER-B이면, word를 tokenizing한 token들 모두에 PER에 해당되는 entity label을 부여하여 학습을 진행하는 것 같은데요,

모든 token들이 아닌, 맨 앞 token만 label을 줘서 학습하는 것과 차이가 클까요?
https://github.com/wzhouad/NLL-IE/blob/main/ner/prepro.py
-> 이 분 NER 코드는 맨 앞 token만 entity label을 줘서 처리하는 것 같더라구요.

제가 생각했을 때는 맨 앞 token만 학습에 활용하는 것이 맞지 않나.. 생각이 들어서
이 부분에 대해 아시는 것이 있으신지 궁금해서 issue남깁니다.

**Comment by sooftware** [comment]
음 이건 선택사항 일 것 같은데요, 저는 전체로 하는게 맞다고 생각해서 진행했습니다.  
'김수환이' 라는 입력이 들어왔을때 토크나이저에 따라서 김/수환/이 가 될 수도 있고 김수/환/이 가 될 수도 있는데, 맨 앞 토큰만 활용했을 때 김수환이 중에 김만 PER로 표기된다거나 하는 문제가 있을 것 같네요.

**Comment by sooftware** [comment]
NER 같은 경우 케릭터 레벨 토크나이저가 아니라면 어떤 방법으로 해도 자잘한 문제는 생길 수 밖에 없을 것 같습니다 :)

**Comment by ZIZUN** [comment]
제 의견은, 말씀 주신대로 '김'이 PER으로 추론되었을 때 '김수환이'를 PER으로 후처리 해주는 작업이 추가될 것을 가정해서 말씀 드린 겁니다 ㅎㅎ!
아마 두 방법에서 evauation 성능 비교시 조금은 다를 것 같은데 한번 비교해 봐야겠습니다.
답변 감사드립니다!

**Comment by sooftware** [comment]
넵 ㅎㅎ :) NER이 제 관심분야는 아니다보니 디테일한 부분은 잘 모르겠네요. 😅  
아마 관련한 실험이나 논문이 있지 않을까 싶긴 하네요.

**Comment by ZIZUN** [comment]
네 조언 감사드립니다.
저도 갑자기 필요해져서 이것저것 찾는 중이라..
다시한번 감사드리고, 연말 잘 보내시길 바랍니다.
그럼 close할게요.
